# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/boop/Packages/Linux_Unreal_Engine_5.5.4

TARGETS = \
	Sky_Engineer-Android-DebugGame  \
	Sky_Engineer-Android-Development  \
	Sky_Engineer-Android-Shipping  \
	Sky_Engineer-Linux-DebugGame  \
	Sky_Engineer-Linux-Development  \
	Sky_Engineer-Linux-Shipping  \
	Sky_Engineer-LinuxArm64-DebugGame  \
	Sky_Engineer-LinuxArm64-Development  \
	Sky_Engineer-LinuxArm64-Shipping  \
	Sky_Engineer \
	Sky_EngineerEditor-Linux-DebugGame  \
	Sky_EngineerEditor-Linux-Development  \
	Sky_EngineerEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Sky_EngineerEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Sky_EngineerEditor-Linux-Debug


Sky_Engineer-Android-DebugGame:
	 $(BUILD) Sky_Engineer Android DebugGame  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-Android-Development:
	 $(BUILD) Sky_Engineer Android Development  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-Android-Shipping:
	 $(BUILD) Sky_Engineer Android Shipping  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-Linux-DebugGame:
	 $(BUILD) Sky_Engineer Linux DebugGame  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-Linux-Development:
	 $(BUILD) Sky_Engineer Linux Development  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-Linux-Shipping:
	 $(BUILD) Sky_Engineer Linux Shipping  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-LinuxArm64-DebugGame:
	 $(BUILD) Sky_Engineer LinuxArm64 DebugGame  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-LinuxArm64-Development:
	 $(BUILD) Sky_Engineer LinuxArm64 Development  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer-LinuxArm64-Shipping:
	 $(BUILD) Sky_Engineer LinuxArm64 Shipping  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_Engineer: Sky_Engineer-Linux-Development

Sky_EngineerEditor-Linux-DebugGame:
	 $(BUILD) Sky_EngineerEditor Linux DebugGame  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_EngineerEditor-Linux-Development:
	 $(BUILD) Sky_EngineerEditor Linux Development  -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" $(ARGS)

Sky_EngineerEditor: Sky_EngineerEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/boop/Documents/Unreal Projects/Sky_Engineer/Sky_Engineer.uproject" -Game 

.PHONY: $(TARGETS)
